version: '3.9'
services:
  app:
    build:
      context: .
      args:
        API_BASE_URL: ${API_BASE_URL:-https://apihomolog.innovationbrindes.com.br}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-https://apihomolog.innovationbrindes.com.br}
        NEXT_PUBLIC_IMAGE_HOST: ${NEXT_PUBLIC_IMAGE_HOST:-innovationbrindes.com.br}
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_IMAGE_HOST=${NEXT_PUBLIC_IMAGE_HOST}
